ADITYA KUMAR SINGH - 118A2101 - EXTC B

Question 1

In [ ]:
import numpy as np

Question 2

In [ ]:
ar=np.zeros(10)
ar

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Question 3

In [ ]:
ar2=np.ones(10)
ar2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Question 4

In [ ]:
ar3=np.ones(10)*5
ar3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Question 5

In [ ]:
ar4=np.arange(10,51)
ar4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Question 6

In [ ]:
ar5=np.arange(10,51,2)
ar5

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Question 7

In [ ]:
ar6=np.arange(0,9).reshape(3,3)
ar6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Question 8

In [ ]:
ar7=np.identity(3)
ar7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Question 9

In [ ]:
ar8=np.random.rand()
ar8

0.8200305294915389

Question 10

In [ ]:
ar9=np.random.normal(0,1,25)
ar9

array([ 0.5448891 , -1.36581975, -0.73094056,  1.42673967,  0.26630512,
       -0.89430391, -0.77341225, -0.4036962 ,  0.42738633,  0.38817036,
        0.80041058, -0.31251861, -0.9703515 , -0.36989176,  0.78278008,
        0.83036158,  0.09794452,  0.42715697, -0.05914295,  0.38055879,
       -0.59357936, -1.72118557,  0.1645253 , -0.47919404, -0.55887302])

Question 11

In [ ]:
ar10=np.linspace(0,1,20)
ar10

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Question 12

In [ ]:
y = np.array([[12, 13, 14, 15],
		[17, 18, 19, 20],
		[22, 23, 24, 25]])
y

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

Question 12.A

In [ ]:
y=y.sum()
y

222

Question 12.B

In [ ]:
dev=np.std(y)
dev

4.232808366400098

Question 12.C

In [ ]:
sum1=np.sum(y,axis=0)
sum1

array([51, 54, 57, 60])

Question 12.D

In [ ]:
output = y[1:3,0:2] #coloum,row
output

array([[17, 18],
       [22, 23]])